import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { StatsProvider } from "./context/stats";
import { FiltersProvider } from "./context/filters";
import { Toaster } from "react-hot-toast";

import { Suspense } from "react";
import Loader from "./_components/loader";

export const metadata: Metadata = {
  title: "DashBoard",
  description: "Generated by Aditya Latta",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body suppressHydrationWarning={true}>
        <TRPCReactProvider>
          <Suspense fallback={<Loader />}>
            <FiltersProvider>
              <StatsProvider>{children}</StatsProvider>
            </FiltersProvider>
          </Suspense>
        </TRPCReactProvider>

        <Toaster />
      </body>
    </html>
  );
}
